version: '3'

services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /run/tailscale/tailscaled.sock:/run/tailscale/tailscaled.sock
      - /datapool/app/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /datapool/app/caddy/config:/config
      - /datapool/app/caddy/data:/data

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /datapool/app/portainer:/data
    ports:
      - 9000:9000

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=131
    volumes:
      - /datapool/app/syncthing/config:/config
      - /datapool/personal:/data1
      - /datapool/media:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
