services:
  portkey:
    image: codehat/portkey:latest
    user: 1000:1000
    ports:
      - "80:3000"
    restart: unless-stopped
    volumes:
      - "/datapool/data/portkey/config.yml:/opt/config.yml"
