apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-ubi-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /datapool/kube
volumeBindingMode: WaitForFirstConsumer