apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: danicos.dev
  namespace: backend
spec:
  secretName: danicos.dev 
  issuerRef:
    name: letsencrypt-dev-wcard
    kind: Issuer
    group: cert-manager.io
  commonName: "*.danicos.dev"
  dnsNames:
    - "danicos.dev"
    - "*.danicos.dev"
