apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: danicos.me
  namespace: backend
spec:
  secretName: danicos.me
  issuerRef:
    name: letsencrypt-dev-wcard
    kind: Issuer
    group: cert-manager.io
  commonName: "*.danicos.me"
  dnsNames:
    - "danicos.me"
    - "*.danicos.me"
