version: '3'

services:
  portainer-agent:
    image: portainer/portainer-ce:latest
    container_name: portainer-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
