services:
  navidrome: 
    image: deluan/navidrome:latest
    user: 1000:1000 # Should be the owner of the volumes.
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "/datapool/data/navidrome:/data"
      - "/datapool/media/music:/music:ro"
